version: '3.8'

services:
  bitbucket:
    image: atlassian/bitbucket-server:latest
    container_name: bitbucket
    ports:
      - "7990:7990"
      - "7999:7999"
    environment:
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket
    volumes:
      - ./bitbucket_data:/var/atlassian/application-data/bitbucket

  jenkins:
    image: akaronte/jenkins-docker:2.504.1
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    environment:

      LDAP_ORGANISATION: "kubedevops"
      LDAP_DOMAIN: "ldap.kubedevops.com"
      LDAP_ADMIN_PASSWORD: "mondariz10"
    tty: true
    stdin_open: true
    volumes:
      - ./ldap:/var/lib/ldap
      - ./slap.d:/etc/ldap/slapd.d
      - ./containers:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "ldap.kubedevops.com"
    hostname: "ldap.kubedevops.com"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8888:80"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_PROXY: edge
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak.kubedevops.com
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_CONTENT_SECURITY_POLICY: frame-src 'self' http://localhost:3000 http://frontend.com http://keycloak.kubedevops.com
    ports:
      - "8081:8080"
      - "8443:8443"
    depends_on:
      - openldap
